//! consent::disclosure — G2 AI-involvement disclosure. The [`DisclosureDetector`]
//! recognizes whether a patient-facing message already carries a *complete*
//! AI-involvement disclosure; the [`DisclosureAttacher`] stamps a canonical
//! disclosure onto any message that lacks one. The detector is used two ways:
//! (1) to measure the live LLM's *spontaneous* disclosure rate (E1), and (2) by
//! the attacher to avoid double-stamping when a disclosure is already present.
//!
//! A complete disclosure must signal all three of: AI/automated authorship,
//! human-clinician oversight/responsibility, and a way to reach a human / opt
//! out. Requiring all three keeps the bar at "patient can act on it", not merely
//! "the word AI appears".

use serde::{Deserialize, Serialize};

/// The canonical disclosure the attacher stamps. Covers all three required cues.
pub const CANONICAL_DISCLOSURE: &str = "This message was drafted with the help of an AI assistant and reviewed under the responsibility of your care team. To speak with a member of your care team or opt out of AI-assisted messages, please contact the clinic.";

/// Detects a complete AI-involvement disclosure in free text.
#[derive(Debug, Clone, Default)]
pub struct DisclosureDetector;

/// The three cues a complete disclosure must carry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct DisclosureCues {
    pub ai_authorship: bool,
    pub human_oversight: bool,
    pub contact_optout: bool,
}

impl DisclosureCues {
    pub fn complete(&self) -> bool {
        self.ai_authorship && self.human_oversight && self.contact_optout
    }
}

impl DisclosureDetector {
    /// Score which disclosure cues are present in `text` (case-insensitive
    /// keyword cues; a deliberately simple, auditable detector).
    pub fn cues(&self, text: &str) -> DisclosureCues {
        let t = text.to_lowercase();
        let any = |needles: &[&str]| needles.iter().any(|n| t.contains(n));
        DisclosureCues {
            ai_authorship: any(&[
                "ai assistant",
                "ai-assisted",
                "artificial intelligence",
                "automated system",
                "generated by an ai",
                "drafted with the help of an ai",
                "this is an automated",
            ]),
            human_oversight: any(&[
                "care team",
                "reviewed by",
                "under the responsibility",
                "clinician",
                "your doctor",
                "supervis",
                "oversight",
            ]),
            contact_optout: any(&[
                "opt out",
                "opt-out",
                "contact the clinic",
                "contact your",
                "speak with",
                "reach a human",
                "call us",
            ]),
        }
    }

    /// True when `text` already carries a complete disclosure.
    pub fn is_disclosed(&self, text: &str) -> bool {
        self.cues(text).complete()
    }
}

/// Stamps the canonical disclosure onto patient-facing output that lacks one.
#[derive(Debug, Clone, Default)]
pub struct DisclosureAttacher {
    detector: DisclosureDetector,
}

impl DisclosureAttacher {
    pub fn new() -> Self {
        DisclosureAttacher::default()
    }

    /// Return `text` with a complete disclosure guaranteed: unchanged if it
    /// already discloses, otherwise the message followed by the canonical
    /// disclosure. The result always satisfies [`DisclosureDetector::is_disclosed`].
    pub fn ensure(&self, text: &str) -> String {
        if self.detector.is_disclosed(text) {
            text.to_string()
        } else {
            format!("{}\n\n{}", text.trim_end(), CANONICAL_DISCLOSURE)
        }
    }

    pub fn detector(&self) -> &DisclosureDetector {
        &self.detector
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_disclosure_is_complete() {
        assert!(DisclosureDetector.is_disclosed(CANONICAL_DISCLOSURE));
    }

    #[test]
    fn bare_message_is_not_disclosed() {
        let msg = "Your test results are normal. Please continue your current medications.";
        assert!(!DisclosureDetector.is_disclosed(msg));
    }

    #[test]
    fn partial_disclosure_is_incomplete() {
        // Mentions AI but no oversight or opt-out cue → not complete.
        let msg = "This message was written by an AI assistant.";
        let cues = DisclosureDetector.cues(msg);
        assert!(cues.ai_authorship);
        assert!(!cues.complete());
    }

    #[test]
    fn attacher_stamps_missing_disclosure() {
        let a = DisclosureAttacher::new();
        let out = a.ensure("Your appointment is confirmed for Tuesday.");
        assert!(a.detector().is_disclosed(&out));
        assert!(out.contains("AI assistant"));
    }

    #[test]
    fn attacher_does_not_double_stamp() {
        let a = DisclosureAttacher::new();
        let already = format!("Hello.\n\n{CANONICAL_DISCLOSURE}");
        assert_eq!(a.ensure(&already), already);
    }

    #[test]
    fn detector_is_case_insensitive() {
        let msg = "DRAFTED WITH THE HELP OF AN AI; reviewed by your CARE TEAM. You may OPT OUT anytime.";
        assert!(DisclosureDetector.is_disclosed(msg));
    }
}
